services:
  # =======================
  # PostgreSQL
  # =======================
  postgres:
    image: postgres:15-alpine
    container_name: app-postgres
    restart: unless-stopped
    env_file:
      - ../envs/.env
    volumes:
      - password_manager_postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - server_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # =======================
  # Redis
  # =======================
  redis:
    image: redis:7-alpine
    container_name: app-redis
    restart: unless-stopped
    networks:
      - server_network

  # =======================
  # Backend (Django)
  # =======================
  backend:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile
    image: password-backend:latest
    container_name: app-backend
    restart: unless-stopped
    env_file:
      - ../envs/.env
    ports:
      - "8000:8000"
    volumes:
      - media_files:/app/src/media
      - static_files:/app/src/staticfiles
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - server_network
    # Entrypoint will wait for the DB, run migrations and collectstatic,
    # then exec the default CMD which starts the server.
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health/" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # =======================
  # Frontend (React)
  # =======================
  frontend:
    build:
      context: ../../../frontend
      dockerfile: Dockerfile
    container_name: app-frontend
    restart: unless-stopped
    environment:
      REACT_APP_API_URL: /
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - server_network

  # =======================
  # Nginx (единственная точка входа)
  # =======================
  nginx:
    image: nginx:alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - "8812:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
      - static_files:/var/www/static
      - media_files:/var/www/media
    depends_on:
      - frontend
      - backend
    networks:
      - server_network

# =======================
# Volumes
# =======================
volumes:
  password_manager_postgres_data:
  static_files:
  media_files:

    # =======================
    # Network
    # =======================
networks:
  server_network:
    driver: bridge
