# Generated by Django 6.0.4 on 2026-04-22 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '__first__'),
        ('product', '0002_productorm_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productorm',
            name='is_encrypted',
            field=models.BooleanField(default=False, verbose_name='Зашифрован'),
        ),
        migrations.AddField(
            model_name='productorm',
            name='password_salt',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Соль для шифрования'),
        ),
        migrations.AddField(
            model_name='productorm',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords', to='organizations.vault', verbose_name='Сейф'),
        ),
        migrations.AlterField(
            model_name='productorm',
            name='password',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Зашифрованный пароль'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка')),
                ('color', models.CharField(blank=True, max_length=7, null=True, verbose_name='Цвет')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='organizations.organization', verbose_name='Организация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.folder', verbose_name='Родительская папка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Папка',
                'verbose_name_plural': 'Папки',
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='productorm',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passwords', to='product.folder', verbose_name='Папка'),
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хеш пароля')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to='product.productorm', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'История пароля',
                'verbose_name_plural': 'Истории паролей',
                'db_table': 'password_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
