# Generated by Django 6.0.4 on 2026-04-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productorm_is_encrypted_productorm_password_salt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorm',
            name='folder',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='passwords',
                to='product.folder'
            ),
        ),
        migrations.AddField(
            model_name='productorm',
            name='vault',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='passwords',
                to='organizations.vault'
            ),
        ),
    ]
